#!/bin/sh

# Script to merge revisions from trunk to the desired branch
# Usage: merge-branch [revisions]
# Kopyleft (K) 2006 by Warp Networks
# All rights reversed

if [ $# -eq 0 ]; then 
    echo "Usage: $0 [revisions]"
    exit 1
fi

BRANCH=~/svn/ebox-platform/branches/0.8

cd $BRANCH

echo "Updating ..."
svn up

echo "Merging ..."
# Starting commit message
svnMessage="Merged "
for rev in $*
do
	prev_rev=$(($rev - 1))
	svn merge -r$prev_rev:$rev https://svn.warp.es/ebox-platform/trunk/
	svnMessage="${svnMessage}[${rev}] "
done

# Completing commit message
if [ $# -gt 1 ]; then
    svnMessage="${svnMessage} revisions"
else
    svnMessage="${svnMessage} revision"
fi
svnMessage="${svnMessage} into branches/0.8"

# Choose a file which does not exist using mktemp 
FILENAME=$(mktemp)

# Make the file have owner-only permissions (Security hack!)
touch $FILENAME
chmod 0600 $FILENAME
echo $svnMessage > $FILENAME

echo "Committing ..."
svn ci --file $FILENAME

rm -f $FILENAME